# Generated by Django 4.2.1 on 2023-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_lineapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Preparando Envio', max_length=50),
        ),
    ]
